### ISSUE TITLE
Getting error when searching only for first 3 letters

### ISSUE THREAD

**Issue by vmalloc** [wangshub/Alfred-Gitlab-Tool#3]
![screen shot 2018-11-11 at 10 20 17](https://user-images.githubusercontent.com/28710/48310687-75921680-e59b-11e8-939b-16332ee75243.png)

Getting this for a project called "stokado" and searching for "sto". When trying "ado" it works fine, so I'm not 100% sure what's going on.

BTW - thanks for this awesome workflow!

**Comment by wangshub** [comment]
@vmalloc Thanks a lot your feedback !

Can you paste your debug log here like this?
![image](https://user-images.githubusercontent.com/20924010/48333813-b2413900-e693-11e8-989d-41c55404ad02.png)

**Comment by vmalloc** [comment]
Sure:
```
Starting debug for 'GitLab-Tool'

[2018-11-14 09:32:40][ERROR: input.scriptfilter] Code 1: .
09:32:40 workflow.py:2055 DEBUG    ---------- GitLab-Tool (1.2.0) ----------
09:32:40 main.py:151 INFO     Namespace(issue=None, merge=False, query=None, repo=u'i', todo=False, token=None, url=None)
09:32:40 workflow.py:1689 DEBUG    loading cached data: /Users/rotemy/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/gitlab_projects.cpickle
09:32:40 workflow.py:1462 DEBUG    reading settings from /Users/rotemy/Library/Application Support/Alfred 3/Workflow Data/settings.json
09:32:40 workflow.py:2074 ERROR    'open_issues_count'
Traceback (most recent call last):
  File "/Users/rotemy/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.ED2E6500-D2AB-43A0-86F1-2682C4873B58/workflow/workflow.py", line 2067, in run
    func(self)
  File "main.py", line 166, in main
    search_gitlab_repo(wf, args.repo)
  File "main.py", line 82, in search_gitlab_repo
    subtitle = "issue:{0: <3} star:{1: <3} fork:{2: <3}".format(proj['open_issues_count'],
KeyError: 'open_issues_count'
09:32:40 workflow.py:2097 DEBUG    ---------- finished in 0.087s ----------
[2018-11-14 09:32:40][ERROR: input.scriptfilter] Code 1: .
09:32:40 workflow.py:2055 DEBUG    ---------- GitLab-Tool (1.2.0) ----------
09:32:40 main.py:151 INFO     Namespace(issue=None, merge=False, query=None, repo=u'inf', todo=False, token=None, url=None)
09:32:40 workflow.py:1689 DEBUG    loading cached data: /Users/rotemy/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/gitlab_projects.cpickle
09:32:40 workflow.py:1462 DEBUG    reading settings from /Users/rotemy/Library/Application Support/Alfred 3/Workflow Data/settings.json
09:32:40 workflow.py:2074 ERROR    'open_issues_count'
Traceback (most recent call last):
  File "/Users/rotemy/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.ED2E6500-D2AB-43A0-86F1-2682C4873B58/workflow/workflow.py", line 2067, in run
    func(self)
  File "main.py", line 166, in main
    search_gitlab_repo(wf, args.repo)
  File "main.py", line 82, in search_gitlab_repo
    subtitle = "issue:{0: <3} star:{1: <3} fork:{2: <3}".format(proj['open_issues_count'],
KeyError: 'open_issues_count'
09:32:40 workflow.py:2097 DEBUG    ---------- finished in 0.063s ----------
```

**Comment by vmalloc** [comment]
@wangshub any idea what's causing it?

**Comment by wangshub** [comment]
this bug might be caused by different version of gitlab api.(my gitlab version: `GitLab Community Edition 11.2.3 1d55bc2`).

I have to know the format of the api response json to fix it

![image](https://user-images.githubusercontent.com/20924010/48986519-3f36c880-f151-11e8-8511-3494ead154d5.png)

@vmalloc

**Comment by vmalloc** [comment]
We are running 11.4.5-ee.

Any specific API you'd like me to post the result of so that you can adjust the code accordingly?

**Comment by wangshub** [comment]
the broken reason is `proj` doesn't have property of `open_issues_count ` https://github.com/wangshub/Alfred-Gitlab-Tool/blob/master/main.py#L82

- you can add `log.info(proj)` to see the reason
- for debug mode, you can just run the `python main.py --repo sto`

@vmalloc

**Comment by wangshub** [comment]
`11.4.5-ee` may have a different  response json format, need to print the response log @vmalloc

**Comment by vmalloc** [comment]
@wangshub no problem, will attach it later today or tomorrow when I have time. Thanks!

**Comment by vmalloc** [comment]
This is what I got:
```
{u'lfs_enabled': True, u'request_access_enabled': True, u'approvals_before_merge': 0, u'forks_count': 1, u'only_allow_merge_if_all_discussions_are_resolved': None, u'http_url_to_repo': u'https://git.myorg.com/host-opensource/infi.storagemodel.git', u'web_url': u'https://git.myorg.com/host-opensource/infi.storagemodel', u'mirror': False, u'wiki_enabled': False, u'id': 111, u'shared_with_groups': [], u'archived': False, u'snippets_enabled': False, u'merge_method': u'merge', u'description': None, u'namespace': {u'kind': u'group', u'name': u'host-opensource', u'parent_id': None, u'path': u'host-opensource', u'id': 7, u'full_path': u'host-opensource'}, u'star_count': 1, u'avatar_url': None, u'_links': {u'repo_branches': u'https://git.myorg.com/api/v4/projects/111/repository/branches', u'merge_requests': u'https://git.myorg.com/api/v4/projects/111/merge_requests', u'self': u'https://git.myorg.com/api/v4/projects/111', u'labels': u'https://git.myorg.com/api/v4/projects/111/labels', u'members': u'https://git.myorg.com/api/v4/projects/111/members', u'events': u'https://git.myorg.com/api/v4/projects/111/events'}, u'resolve_outdated_diff_discussions': None, u'issues_enabled': False, u'path_with_namespace': u'host-opensource/infi.storagemodel', u'ci_config_path': None, u'merge_requests_enabled': True, u'default_branch': u'develop', u'visibility': u'internal', u'readme_url': u'https://git.myorg.com/host-opensource/infi.storagemodel/blob/develop/README.md', u'ssh_url_to_repo': u'git@git.myorg.com:host-opensource/infi.storagemodel.git', u'public_jobs': True, u'path': u'infi.storagemodel', u'import_status': u'none', u'only_allow_merge_if_pipeline_succeeds': False, u'last_activity_at': u'2018-11-11T15:33:51.898Z', u'name': u'infi.storagemodel', u'printing_merge_request_link_enabled': True, u'name_with_namespace': u'host-opensource / infi.storagemodel', u'created_at': u'2015-04-04T18:23:48.576Z', u'creator_id': 4, u'shared_runners_enabled': True, u'container_registry_enabled': None, u'permissions': {u'project_access': None, u'group_access': {u'notification_level': 3, u'access_level': 30}}, u'tag_list': [], u'jobs_enabled': False}
```

**Comment by wangshub** [comment]
I see, your gitlab repo`"issues_enabled": false`, but mine is `true`, and if `false`, gitlab api doesn't return `open_issues_count ` , I will fix it 

@vmalloc

**Comment by vmalloc** [comment]
@wangshub Thanks! Much appreciated

**Comment by wangshub** [comment]
[GitLab-Tool.zip](https://github.com/wangshub/Alfred-Gitlab-Tool/files/2619187/GitLab-Tool.zip)

@vmalloc can you try this?

**Comment by wangshub** [comment]
@vmalloc https://github.com/wangshub/Alfred-Gitlab-Tool/pull/4

**Comment by vmalloc** [comment]
Seems to be working!

**Comment by vmalloc** [comment]
@wangshub is the version containing the fix available already?

**Comment by wangshub** [comment]
sure, fresh release https://github.com/wangshub/Alfred-Gitlab-Tool/releases/tag/1.2.1 

@vmalloc

**Comment by vmalloc** [comment]
@wangshub cool! thanks a lot!
